logLevel: INFO
kiosks:
    breakable:
        title: '§4!Break!'
        trigger: '!break!?'
    punchable:
        title: '§4!Punch!'
        trigger: '!punch!?'
functions: # 1 = Player Name, 2 = Player Display Name, 3 = 3rd Sign Line, 4 = 4th Sign Line, 5 = World, 6 = Block X, 7 = Block Y, 8 = Block Z
    Claim:
        use: kiosk.use.claim
        denied: '-> You §ccan not claim§r more than one plot'
        apply: kiosk.apply.claim
        description:
            - '-> Break this sign to claim {3}'
            - '-> You can only claim one plot'
            - '-> Compare first to §ebe sure you want this plot!'
        dispatch:
            - p+ kiosk.use.claim false {1}
            - simpleregions:region.owners.reset {1} {3} {5}
            - 'simpleregions:region.rename "{1} Residence" {3} {5}'
            - 'send {1} -> {3} renamed to "{1} Residence"'
permissions:
    kiosk.use.claim:
        default: false
messages:
    applyDenied: '-> You are §cnot allowed§r to apply kiosk function: {1}' # 1 = Function
    createFailed: '-> Kiosk §ccreation failed'
    createSuccess: '-> Kiosk §2created successfully'
    removeCancel: '-> Kiosk §cremoval cancelled'
    unknownKiosk: '-> §cUnable to determine§r kiosk'
    unknownFunction: '-> §cUnable to determine§r kiosk function: {1}' # 1 = Function
    unknownWorld: '-> §cUnable to determine§r World: {1}' # 1 = <World>
    requiresPlayer: '-> §cOnly in-game players§r can use the {1} command' # 1 = Command Label
    reload: '-> {1} plugin §2reloaded' # 1 = Plugin Name
version: @VERSION@